//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KarmaZapotrzebowanie
    {
        public int Zap_GIDNumer { get; set; }
        public int Zap_GatNumer { get; set; }
        public string Zap_NazwaKarmy { get; set; }
        public decimal Zap_IloscAktualna { get; set; }
        public decimal Zap_IloscPotrzebna { get; set; }
        public string Zap_Jm { get; set; }
    
        public virtual Gatunek Gatunek { get; set; }
    }
}
