//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kojec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kojec()
        {
            this.Zwierze = new HashSet<Zwierze>();
        }
    
        public int Koj_GIDNumer { get; set; }
        public int Koj_StrNumer { get; set; }
        public string Koj_Kod { get; set; }
        public string Koj_Nazwa { get; set; }
    
        public virtual Strefa Strefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zwierze> Zwierze { get; set; }
    }
}
