//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KsiazeczkaZdrowiaNag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KsiazeczkaZdrowiaNag()
        {
            this.KsiazeczkaZdrowiaElem = new HashSet<KsiazeczkaZdrowiaElem>();
            this.Leczenie = new HashSet<Leczenie>();
        }
    
        public int KzN_GIDNumer { get; set; }
        public int KzN_ZwrNumer { get; set; }
        public string KzN_Nazwa { get; set; }
        public System.DateTime KzN_DataUtworzenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KsiazeczkaZdrowiaElem> KsiazeczkaZdrowiaElem { get; set; }
        public virtual Zwierze Zwierze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leczenie> Leczenie { get; set; }
    }
}
