//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimalShelterEntities : DbContext
    {
        public AnimalShelterEntities()
            : base("name=AnimalShelterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Gatunek> Gatunek { get; set; }
        public virtual DbSet<KarmaZapotrzebowanie> KarmaZapotrzebowanie { get; set; }
        public virtual DbSet<Kojec> Kojec { get; set; }
        public virtual DbSet<KsiazeczkaZdrowiaElem> KsiazeczkaZdrowiaElem { get; set; }
        public virtual DbSet<KsiazeczkaZdrowiaNag> KsiazeczkaZdrowiaNag { get; set; }
        public virtual DbSet<Leczenie> Leczenie { get; set; }
        public virtual DbSet<Strefa> Strefa { get; set; }
        public virtual DbSet<Zdjecie> Zdjecie { get; set; }
        public virtual DbSet<Zwierze> Zwierze { get; set; }
    }
}
