//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strefa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Strefa()
        {
            this.Kojec = new HashSet<Kojec>();
        }
    
        public int Str_GIDNumer { get; set; }
        public int Str_GatNumer { get; set; }
        public string Str_Kod { get; set; }
        public string Str_Nazwa { get; set; }
    
        public virtual Gatunek Gatunek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kojec> Kojec { get; set; }
    }
}
