//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zdjecie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zdjecie()
        {
            this.Zwierze1 = new HashSet<Zwierze>();
        }
    
        public int Zdj_GIDNumer { get; set; }
        public int Zdj_ZwrNumer { get; set; }
        public string Zdj_Tytul { get; set; }
        public string Zdj_Sciezka { get; set; }
    
        public virtual Zwierze Zwierze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zwierze> Zwierze1 { get; set; }
    }
}
