//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zwierze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zwierze()
        {
            this.KsiazeczkaZdrowiaNag = new HashSet<KsiazeczkaZdrowiaNag>();
            this.Zdjecie = new HashSet<Zdjecie>();
        }
    
        public int Zwr_GIDNumer { get; set; }
        public int Zwr_GatNumer { get; set; }
        public string Zwr_Imie { get; set; }
        public System.DateTime Zwr_DataPrzyjecia { get; set; }
        public string Zwr_Plec { get; set; }
        public Nullable<int> Zwr_Avatar { get; set; }
        public string Zwr_Opis { get; set; }
        public string Zwr_Rasa { get; set; }
        public Nullable<int> Zwr_KojNumer { get; set; }
    
        public virtual Gatunek Gatunek { get; set; }
        public virtual Kojec Kojec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KsiazeczkaZdrowiaNag> KsiazeczkaZdrowiaNag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zdjecie> Zdjecie { get; set; }
        public virtual Zdjecie Zdjecie1 { get; set; }
    }
}
